# Generated by Django 5.2.8 on 2025-12-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('product_interest', models.CharField(choices=[('kurtis', 'Kurtis'), ('short_kurtis', 'Short Kurtis'), ('tops', 'Tops'), ('jeans', 'Jeans'), ('multiple', 'Multiple Categories'), ('all', 'All Products')], max_length=50)),
                ('estimated_quantity', models.CharField(blank=True, help_text='e.g., 500-1000 pieces', max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_responded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
