# Generated by Django 5.2.8 on 2025-12-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('kurtis', 'Kurtis'), ('short_kurtis', 'Short Kurtis'), ('tops', 'Tops'), ('jeans', 'Jeans')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('min_order_quantity', models.PositiveIntegerField(default=50)),
                ('price_range', models.CharField(blank=True, help_text='e.g., ₹250 - ₹450', max_length=100)),
                ('fabric', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
