# Generated by Django 5.2.8 on 2026-06-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_range',
            field=models.CharField(blank=True, help_text='e.g., ₹250', max_length=100, verbose_name='Price'),
        ),
    ]
