# Generated by Django 5.2.8 on 2026-06-18 16:29

import django.db.models.deletion
from django.db import migrations, models


def migrate_data_forward(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Unit = apps.get_model('products', 'Unit')
    Product = apps.get_model('products', 'Product')
    
    # Create default categories matching the original CATEGORY_CHOICES
    kurtis = Category.objects.create(
        name='Kurtis', 
        slug='kurtis', 
        description='Elegant floral and casual kurtis'
    )
    short_kurtis = Category.objects.create(
        name='Short Kurtis', 
        slug='short_kurtis', 
        description='Casual and trendy short kurtis'
    )
    tops = Category.objects.create(
        name='Tops', 
        slug='tops', 
        description='Floral and modern western tops'
    )
    jeans = Category.objects.create(
        name='Jeans', 
        slug='jeans', 
        description='Classic skinny, straight, and bootcut jeans'
    )
    
    category_map = {
        'kurtis': kurtis,
        'short_kurtis': short_kurtis,
        'tops': tops,
        'jeans': jeans,
    }
    
    # Create default unit (Piece/pcs)
    pcs = Unit.objects.create(
        name='Piece', 
        short_name='pcs'
    )
    
    # Update existing products to link to new Category and Unit records
    for product in Product.objects.all():
        old_cat = product.category_old
        product.category = category_map.get(old_cat)
        product.unit = pcs
        product.save()


def migrate_data_backward(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        if product.category:
            product.category_old = product.category.slug
            product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_price_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_old',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Piece, Box, Meter', max_length=50)),
                ('short_name', models.CharField(help_text='e.g., pcs, box, m', max_length=10)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.unit'),
        ),
        migrations.RunPython(
            code=migrate_data_forward,
            reverse_code=migrate_data_backward,
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_old',
        ),
    ]
